name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy:
      needs: build
      runs-on: self-hosted

      steps:
      - name: Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: war file
          path: /home/aishwarya/actionrunner/_work/employee_registration/employee_registration/target/employee_registration-2.2-SNAPSHOT.war      
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: war file
          path: sudo /opt/tomcat/webapps
